### PR TITLE
Corrected imports.

### PR DESCRIPTION
**Pull request by ABossOfMyself**
made some major corrections!

### CODE REVIEW

**Comment by Robbe98** [comment]
That is how the imports are structured in the demo code:
https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/main/deploy/01-deploy-raffle.js
And my script won't work with only one period.  It has to go back to the main directory in order to find the helper-config file and utils folder...so that's why two periods, no?

**Comment by ABossOfMyself** [comment]
> That is how the imports are structured in the demo code: https://github.com/PatrickAlphaC/hardhat-smartcontract-lottery-fcc/blob/main/deploy/01-deploy-raffle.js And my script won't work with only one period. It has to go back to the main directory in order to find the helper-config file and utils folder...so that's why two periods, no?

@Robbe98 If your directory is just like your repo then my PR is correct, You should try it out!

**Comment by ABossOfMyself** [comment]
@ABossOfMyself : Patrick's directory is not same as your's,

-  He has `verify.js` in _utils folder_.
- and `01-deploy-raffle.js` in _deploy folder._

Hopefully you will get my point!

**Comment by Robbe98** [comment]
I have those files in folders...just didn't post the folder on github. 
In any event, I've managed to deploy successfully to RINKEBY and verify it.  https://rinkeby.etherscan.io/address/0x89E4Ccd624184abdDd702272EBa262DB2C4b5260#code

I will try GOERLI later in the day...

But thank you for your help, it's much appreciated.

**Comment by ABossOfMyself** [comment]
> I have those files in folders...just didn't post the folder on github. In any event, I've managed to deploy successfully to RINKEBY and verify it. https://rinkeby.etherscan.io/address/0x89E4Ccd624184abdDd702272EBa262DB2C4b5260#code
> 
> I will try GOERLI later in the day...
> 
> But thank you for your help, it's much appreciated.

@Robbe98 : Awesome! You Welcome.

**Pull request closed without merging**
